Algoritmo "Pagina66ExF"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Pedro Ferreira da Silva
// Autor(a)    : Pedro Ferreira da Silva
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 1 ate 199 faca
se(n mod 4 = 0)entao
Escreval(n)
fimse
fimpara

Fimalgoritmo