Algoritmo "Exibir Mensagem"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem (função)
// Autor(a)    : Pedro Ferreira da Silva
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Pedro")
Escreval("Equipe 04")
Escreval("Teste 01")

Fimalgoritmo